spring:
  cloud:
    function:
      # Function definition names
      definition: eventProcessor;eventListener;dlqEventListener
    stream:
      bindings:
        # Event processor input Spring Cloud Stream general binder definition
        eventProcessor-in-0:
          group: group-name
          destination: event-input
          consumer:
            max-attempts: 1
            batch-mode: true
            use-native-decoding: true
        # Event processor output Spring Cloud Stream general binder definition
        eventProcessor-out-0:
          destination: event-output
          producer:
            use-native-encoding: true
        # Event listener Spring Cloud Stream general binder definition
        eventListener-in-0:
          group: group-name
          destination: event-output
          consumer:
            max-attempts: 1
            use-native-decoding: true
        # DLQ event listener Spring Cloud Stream general binder definition
        dlqEventListener-in-0:
          group: group-name
          destination: event-dlq
          consumer:
            max-attempts: 1
            use-native-decoding: true
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          # Event processor input Spring Cloud Stream binder specific definition
          eventProcessor-in-0:
            consumer:
              configuration:
                # Event processor error handling deserializer
                # https://docs.spring.io/spring-cloud-stream/docs/3.2.x/reference/html/spring-cloud-stream-binder-kafka.html#_handling_deserialization_errors_with_dlq
                value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.trusted.packages: com.example.demo
              # Event processor Spring Cloud Stream Kafka DLQ configuration
              # https://docs.spring.io/spring-cloud-stream/docs/3.2.x/reference/html/spring-cloud-stream-binder-kafka.html#_simple_dlq_with_kafka
              enable-dlq: true
              dlq-name: event-dlq
              dlq-producer-properties:
                configuration:
                  key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
                  value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          # Event processor output Spring Cloud Stream binder specific definition
          eventProcessor-out-0:
            producer:
              configuration:
                value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          # Event listener Spring Cloud Stream binder specific definition
          eventListener-in-0:
            consumer:
              configuration:
                value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.trusted.packages: com.example.demo
          # DLQ event listener Spring Cloud Stream binder specific definition
          dlqEventListener-in-0:
            consumer:
              configuration:
                value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.trusted.packages: com.example.demo